// Seed data: pages and sections for the CMS
// This is the source of truth for what sections exist on each page

export const PAGES = [
  { slug: "home", name: "Home" },
  { slug: "about-us", name: "About Us" },
  { slug: "leadership-and-team", name: "Leadership & Team" },
  { slug: "schedule-demo", name: "Schedule Demo" },
  { slug: "contact-us", name: "Contact Us" },
  { slug: "thank-you", name: "Thank You" },
];

export const SECTIONS_BY_PAGE: Record<string, { component_name: string; display_name: string }[]> = {
  home: [
    { component_name: "BannerSection", display_name: "Hero Banner" },
    { component_name: "FmcgSection", display_name: "FMCG Portfolio" },
    { component_name: "B2bSection", display_name: "B2B Section (ThirdMeta)" },
    { component_name: "EducationSection", display_name: "Education Section (EduHexa)" },
    { component_name: "WhatDefinesUsSection", display_name: "What Defines Us" },
    { component_name: "LogoMarqueeSection", display_name: "Logo Marquee (Client Logos)" },
    { component_name: "WhyWeStartedSection", display_name: "Why We Started" },
    { component_name: "SolutionsSection", display_name: "Solutions" },
    { component_name: "WhyChooseUsSection", display_name: "Why Choose Us" },
    { component_name: "TeamCultureSection", display_name: "Team & Culture" },
    { component_name: "TestimonialSection", display_name: "Testimonials Carousel" },
    { component_name: "ValuesApproachSection", display_name: "Values & Approach" },
    { component_name: "AwardsLogoWallSection", display_name: "Awards Logo Wall" },
    { component_name: "ResourcesSection", display_name: "Resources" },
    { component_name: "TestimonialsHeaderSection", display_name: "Growth Systems CTA" },
    { component_name: "FaqSection", display_name: "FAQ" },
    { component_name: "DemoFormSection", display_name: "Contact Form" },
    { component_name: "TagsCarouselSection", display_name: "Tags Carousel" },
    { component_name: "FooterSection", display_name: "Footer" },
  ],
  "about-us": [
    { component_name: "GlobalHeader", display_name: "Global Header" },
    { component_name: "LeadershipHeroSection", display_name: "Hero Section" },
    { component_name: "AboutIntroSection", display_name: "About Intro" },
    { component_name: "SolutionsSection", display_name: "Solutions" },
    { component_name: "WhyWeStartedSection", display_name: "Why We Started" },
    { component_name: "WhatDefinesUsSection", display_name: "What Defines Us" },
    { component_name: "AboutMissionVisionSection", display_name: "Mission & Vision" },
    { component_name: "AboutJourneySection", display_name: "Our Journey Gallery" },
    { component_name: "AboutContactSection", display_name: "Contact Form" },
    { component_name: "AboutEcosystemSection", display_name: "Ecosystem" },
    { component_name: "AboutEcosystemAccordionSection", display_name: "Ecosystem Accordion" },
    { component_name: "TeamCultureSection", display_name: "Team & Culture" },
    { component_name: "AboutB2BPortfolioSection", display_name: "B2B Portfolio" },
    { component_name: "ValuesApproachSection", display_name: "Values & Approach" },
    { component_name: "TestimonialsHeaderSection", display_name: "Growth Systems CTA" },
    { component_name: "AwardsLogoWallSection", display_name: "Awards Logo Wall" },
    { component_name: "TagsCarouselSection", display_name: "Tags Carousel" },
    { component_name: "FooterSection", display_name: "Footer" },
  ],
  "leadership-and-team": [
    { component_name: "GlobalHeader", display_name: "Global Header" },
    { component_name: "LeadershipHeroSection", display_name: "Hero Section" },
    { component_name: "WhatDefinesUsSection", display_name: "What Defines Us" },
    { component_name: "LogoMarqueeSection", display_name: "Logo Marquee" },
    { component_name: "WhyWeStartedSection", display_name: "Why We Started" },
    { component_name: "TeamCultureSection", display_name: "Team & Culture" },
    { component_name: "LeadershipWhyChooseUsSection", display_name: "Why Choose Us" },
    { component_name: "LeadershipTestimonialSection", display_name: "Testimonials" },
    { component_name: "B2bSection", display_name: "B2B Portfolio" },
    { component_name: "ValuesApproachSection", display_name: "Values & Approach" },
    { component_name: "LeadershipGallerySection", display_name: "Image Gallery" },
    { component_name: "AboutContactSection", display_name: "Contact Form" },
    { component_name: "LeadershipGrowthSystemsSection", display_name: "Growth Systems CTA" },
    { component_name: "FooterSection", display_name: "Footer" },
  ],
  "schedule-demo": [
    { component_name: "BookStrategyCallSection", display_name: "Book Strategy Call Form" },
    { component_name: "WhyChooseUsSection", display_name: "Why Choose Us" },
    { component_name: "FaqSection", display_name: "FAQ" },
    { component_name: "TestimonialsHeaderSection", display_name: "Growth Systems CTA" },
  ],
  "contact-us": [
    { component_name: "DemoFormSection", display_name: "Contact Form" },
    { component_name: "ContactInfoSection", display_name: "Contact Info & Map" },
    { component_name: "LogoMarqueeSection", display_name: "Logo Marquee" },
    { component_name: "TestimonialsHeaderSection", display_name: "Growth Systems CTA" },
    { component_name: "TestimonialSection", display_name: "Testimonials" },
    { component_name: "TagsCarouselSection", display_name: "Tags Carousel" },
  ],
  "thank-you": [
    { component_name: "ThankYouBanner", display_name: "Thank You Banner" },
    { component_name: "WhyChooseUsSection", display_name: "Why Choose Us" },
    { component_name: "TestimonialsHeaderSection", display_name: "Growth Systems CTA" },
    { component_name: "TestimonialSection", display_name: "Testimonials" },
    { component_name: "TagsCarouselSection", display_name: "Tags Carousel" },
    { component_name: "FaqSection", display_name: "FAQ" },
  ],
};
